version: "3.9"
services:
  server:
    container_name: express
    build:
      context: ./express-app
      dockerfile: Dockerfile
    command: "npm run start:dev"
    ports:
      - "8080:8080"

  client:
    container_name: react
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    command: "npm run start"
    volumes:
      - ./react-frontend/src:/usr/src/app/src
      - ./react-frontend/public:/usr/src/app/public
    ports:
      - "3000:3000"
    depends_on:
      - server
      
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db